repo:  https://github.com/openwrt/openwrt.git
branch: openwrt-21.02
revision: c67509efd7d0c43eb3f622f06c8a31aa28d22f6e
output_dir: ./output

patch_folders:
  - patches/backports/
  - patches/base
  - patches/wifi
  - patches/ath79
  - patches/ramips
  - patches/ipq40xx
  - patches/ipq806x
  - patches/ipq807x
  - patches/rtkmipsel
  - patches/rest
  - patches/mediatek-sdk
  - patches/minim
